### ISSUE TITLE
Set NPM_AUTH somewhere

### ISSUE THREAD

**Issue by jonah-williams** [goodeggs/developer-start#29]
Developer-start doesn't appear to set NPM_AUTH anywhere. It sounds like most people set this manually in their shell's dot files but maybe we can do better or at least document if it is a required manual config step?

**Comment by demands** [comment]
:+1:

**Comment by randypuro** [comment]
Not sure if this is right, but I exported the value of _auth from ~/.npmrc as NPM_AUTH in my ~/.sekret.

**Comment by randypuro** [comment]
Fixed here:
https://github.com/goodeggs/developer-start/commit/b86d22f05aedcb90e1013f41aca4743b0cbdc22c
