### ISSUE TITLE
Does not install nvmish

### ISSUE THREAD

**Issue by serhalp** [goodeggs/developer-start#34]

**Comment by hurrymaplelad** [comment]
From [PR notes](https://github.com/goodeggs/garbanzo/pull/2466)

Development Environment Changes

Now that you'll have some apps on Node 0.10 and some on Node 0.12, I suggest installing nvmish, a little utility that will change your nvm version based on the value of engines.node in the current directory's package.json.
```
brew tap goodeggs/delivery-eng
brew install nvmish
# follow the instructions; reload your shell

cd garbanzo
rm -rf node_modules && npm install

```

**Comment by hurrymaplelad** [comment]
See also https://github.com/goodeggs/homebrew-delivery-eng/issues/1.  Perhaps we should go straight to nodenv when we fix this.

**Comment by bobzoller** [comment]
:+1:
