### ISSUE TITLE
Does not setup GoodEggs dropbox

### ISSUE THREAD

**Issue by hurrymaplelad** [goodeggs/developer-start#43]
@andreeee is this something handled at machine provisioning time, or should we add it to our developer-start script?

Related to #36

**Comment by hurrymaplelad** [comment]
This looks promising:
https://github.com/caskroom/homebrew-cask/blob/master/Casks/dropbox.rb

`brew cask install dropbox`?

**Comment by jonah-williams** [comment]
Dropbox is now installed (see #52). Manual invites to shared folders are required but I can't think of a way to automate that while maintaining appropriate access controls.
